### ISSUE TITLE
Connecting to lennoxicomfort.com vs myicomfort.

### ISSUE THREAD

**Issue by mattgreeley** [thevoltagesource/myicomfort#3]
Do you know if anyone has done a similar project that connects to 
lennoxicomfort.com (vs myicomfort.com)?

**Comment by thevoltagesource** [comment]
For this API someone had already figured out the interaction process with Lennox and I was able to extend that work to build a complete wrapper. I haven't found anyone that has create a similar API wrapper or even done a similar investigation and published their results.  I did start doing some investigation of my own since I now own a S30 but the interaction it is very different and I am still trying to understand all the pieces.

**Comment by thevoltagesource** [comment]
I never got anywhere with the project but someone did. Check out this [repository](https://github.com/PeteRager/lennoxs30api).
